services:
  - type: web
    name: school-timetable
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn timetable_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
